### ISSUE TITLE
Logout Mercadolibre

### ISSUE THREAD

**Issue by uncodead** [mercadolibre/php-sdk#23]
How can i clear the ML cokies?? I Want to logout MercadoLibre acount.

**Comment by sirgotisa** [comment]
Same problem. I want to logout from my android app but the url does not:
 String url = "https://www.mercadolibre.com/jms/mlm/lgz/logout?go=http://www.mercadolibre.com.mx";

I have read a lot of information but I don't understand why this does not work. Am I supposed to never logout from the app????? How did you solve this?

**Comment by rodrigojob** [comment]
Don't exist logout in API, any API. You can delete access_token information in your software.
But, the best way is you have login control in your software.
For any questions use developers-forum.mercadolibre.com

**Comment by e-lyder** [comment]
Eu uso no Laravel.

```php
public function logout() {
    if(session('profile')) {
        session()->forget('profile');
        session()->flush();
    }
    return Redirect::to('/meliapp/login');
}
```
