### ISSUE TITLE
Porque me redirecciona a ML Brasil?

### ISSUE THREAD

**Issue by juanmas07** [mercadolibre/php-sdk#38]
Estoy usando la api, pero solo me redirecciona a ML Brasil, necesitaría que me loguee en el sitio de Argentina.

echo '<a href="' . $meli->getAuthUrl('http://localhost/versioned/software/meli-connect/list.php') . '">Login using MercadoLibre oAuth 2.0</a>';

**Comment by nlegresti** [comment]
En meli.php debes cambiar el $AUTH_URL a:
static $AUTH_URL = "http://auth.mercadolibre.com.ar/authorization";
