### ISSUE TITLE
204 no content

### ISSUE THREAD

**Issue by canizalezDaniel** [mercadolibre/php-sdk#62]
Intentando publicar un producto bajo el siguiente JSON de prueba
{
"title":"Item de test - No Ofertar",
"category_id":"MLC3530",
"price":10,
"currency_id":"CLP",
"available_quantity":5,
"buying_mode":"buy_it_now",
"listing_type_id":"bronze",
"description": "Item de test - No Ofertar",
"condition": "used",
"pictures":[{"source":"http://santanaelectricalservice.com.ve/imagenes/importamostodo.jpg"}]
	
}
Pero siempre obtengo como respuesta 204 no content, the server succesfully processed the request but is no returning any content.

Como puedo empezar a publicar en producción.

Saludos,

**Comment by lscortesc** [comment]
¿A qué URL estás haciendo el POST @canizalezDaniel? Si no me equivocó al parecer estás haciendo la petición a la [url](http://developers.mercadolibre.com/es/validador-de-publicaciones/) para verificar los datos de tu petición, que si todo va bien te devuelve un 204 como respuesta, una vez que ya haz validado tus datos, debes hacer el post a otra URL para publicarlo.

- URL Validador `https://api.mercadolibre.com/items/validate?access_token=$ACCESS_TOKEN`
- URL Publicar Item `https://api.mercadolibre.com/items?access_token=$ACCESS_TOKEN`

[Referencia Validador Items](http://developers.mercadolibre.com/es/validador-de-publicaciones/)
[Referencia Items](http://developers.mercadolibre.com/es/publica-productos/#Publica-un-articulo)

**Comment by canizalezDaniel** [comment]
Ops! muy mala de mi parte, deje en postman validate y no el recurso items. Muchisimas gracias.

**Comment by lscortesc** [comment]
Excelente! 👍
