### ISSUE TITLE
Me denunciaron la cuenta por usar un codigo ejemplo

### ISSUE THREAD

**Issue by nachodallago** [mercadolibre/php-sdk#76]
Gente, me acaban de denunciar una publicacion porque "infringiría sus derechos de autor (ej: copia ilegal de una película, un video, un libro, una pintura)". Y sólo usé el código de ejemplo que está en este SDK. 

ARREGLEN ESTO O CAMBIEN EL CODIGO DE EJEMPLO. 
SI ME BLOQUEAN LA CUENTA LOS VOY A ESCRACHAR.

**Comment by ruevers** [comment]
> Gente, me acaban de denunciar una publicacion porque "infringiría sus derechos de autor (ej: copia ilegal de una película, un video, un libro, una pintura)". Y sólo usé el código de ejemplo que está en este SDK.
> 
> ARREGLEN ESTO O CAMBIEN EL CODIGO DE EJEMPLO.
> SI ME BLOQUEAN LA CUENTA LOS VOY A ESCRACHAR.

Why you are so rude man???

**Comment by nachodallago** [comment]
> Why you are so rude man???

I was angry because I was going to lose my account, I'm sorry. Anyway, they already contacted me and the problem was solved👍
